config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :pictures, only: [:create, :edit, :update, :destroy]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show] do
    resources :pictures, only: [:show]
  end
  resources :searches, only: [:index]

  root 'welcome#index'
  get '/users/:id/views', to: 'users#views', as: "views"
  post '/users/:id/association', to: 'users#association'
  get '/users/:id/follower_requests', to: 'users#follower_requests', as: "request"
  post '/searchPicture', to: 'searches#searchPicture'
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :tags, through: :picture_tags
  has_many :picture_tags
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :location
  validates :avatar, presence: :true

  scope :most_recent, -> { order(created_at: :asc)}
  scope :picture_collector, -> ids {where(id: ids)}

  def location_attributes=(attributes)
    if attributes[:title] != "" && attributes[:address] != ""
      if self.location
        self.errors.messages[:bad_location] = ["can only choose one location"]
      else
        self.location = Location.find_or_create_by(attributes)
      end
    elsif one_blank(attributes)
      self.errors.messages[:bad_location] = ["location must contain a title and an address"]
    end
  end

  def tags_attributes=(attributes)
    if !attributes["0"].values.include?("")
      attributes.values.each do |key|
        self.tags << Tag.find_or_create_by(key)
      end
    end
  end

  def one_blank(attributes)
    if (attributes[:title] != "" && attributes[:address] == "") ||
      (attributes[:title] == "" && attributes[:address] != "")
      true
    else
      false
    end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:edit, :update, :show, :destroy]

  def create
    @picture = Picture.new(picture_params)
    if @picture.errors.any? || !@picture.save
      render json: @picture.errors.messages, status: 422
    else
      @picture.save
      render json: @picture
    end
  end

  def show
    @comment = Comment.new(picture: @picture, user: current_user)
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @picture}
    end

  end

  def edit
    respond_to do |f|
      f.html { render :edit }
      f.json { render :edit }
    end
  end

  def update

    @picture.assign_attributes(picture_params)
    if @picture.errors.any? || !@picture.save
      render json: @picture.errors.messages, status: 422
    else
      @picture.save
      render json: @picture
    end
  end

  def destroy
    response = {picture:"card.#{@picture.id}"}
    @picture.destroy
    render json: response
  end

  private

  def set_picture
    @picture = Picture.find_by(id: params[:id])
    @user = @picture.user
    if params[:action] == "edit"
      set_location
    end
  end

  def set_location
    @location = @picture.location
  end

  def picture_params
    params.require(:picture).permit(:title, :avatar, :user_id, :location_id, tag_ids:[],
                  location_attributes:[:title, :address], tags_attributes: [:title])
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def both_location?(params)
    !params[:location_attributes].values.join("").empty? && !params[:location_id].empty?
  end

  def count_errors(picture)
    location_errors = 0
    if picture.location
      location_errors = picture.location.errors.count
    end
    pluralize(picture.errors.count + location_errors, "error")
  end

end

app/views/pictures/_form.html.erb
<% if user == current_user %>
  <%= form_for picture, :html => { id:"nestedForm", class:"newPicture ui modal"} do |f| %>
    <div class="formContent">
    <% if params[:action] != "edit" %>
    <%= f.file_field :avatar%><br><br>
    <% end %>
    <%= f.label :title, "Picture Title" %><br>
    <%= f.text_field :title, class: "formTextBox" %><br><br>
    <%= f.label "Create Location:" %><br>
    <%= f.fields_for :location, picture.build_location do |i| %>
    <%= i.label :title %><br>
    <%= i.text_field :title, class: "formTextBox", value: @location.title %><br>
    <%= i.label :address %><br>
    <%= i.text_field :address, class: "formTextBox", value: @location.address %>
    <% end %><br><br>
    Select Existing Location:<br>
    <%= f.collection_select :location_id, Location.all, :id, :title, :include_blank => true %><br><br>

    <%= f.label "Create Tag:" %><br>
    <%= f.fields_for :tags, picture.tags.build do |i| %>
    <%= i.text_field :title, class: "formTextBox" %>
    <% end %><br><br>
    Select Existing Tags:<br>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :title %><br><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% if params[:action] == "edit" %>
    <%= f.button " Edit Picture", id:"submitButton"  %>
    <% else %>
    <%= f.button " Post Picture", id:"submitButton"  %>
    <% end %>
  </div>
  <% end %>

<% end %>
<input type="hidden" name="parseForm">

app/views/pictures/_picture.html.erb
<!-- <br><br><br>
<% if !picture.title.empty? %>
  <%= picture.title %> <br>
<% end %>
<%= picture.location.title %> <br>
<%= picture.location.address %> <br>

<a href="<%= user_picture_path(current_user, picture) %>"><%= image_tag picture.avatar.url %></a>
<% if current_user == picture.user %>
  <%= button_to "edit", edit_picture_path(picture), method: :get %>
  <%= button_to "delete", picture_path(picture), method: :delete%>

<% end %>
<br><br><br> -->

app/views/pictures/edit.html.erb
<input type="hidden" name="parseForm">
<% if @user == current_user %>
  <%= form_for @picture, :html => { id:"nestedForm", class:"ui modal newForm"} do |f| %>
    <div class="formContent">
    <% if params[:action] != "edit" %>
    <%= f.file_field :avatar%><br><br>
    <% end %>
    <%= f.label :title, "Picture Title" %><br>
    <%= f.text_field :title %><br><br>
    <%= f.label "Create Location:" %><br>
    <%= f.fields_for :location, @picture.build_location do |i| %>
    <%= i.label :title %><br>
    <%= i.text_field :title, value: @location.title %><br>
    <%= i.label :address %><br>
    <%= i.text_field :address, value: @location.address %>
    <% end %><br><br>
    Select Existing Location:<br>
    <%= f.collection_select :location_id, Location.all, :id, :title, :include_blank => true %><br><br>

    <%= f.label "Create Tag:" %><br>
    <%= f.fields_for :tags, @picture.tags.build do |i| %>
    <%= i.text_field :title %>
    <% end %><br><br>
    Select Existing Tags:<br>
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :title %><br><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% if params[:action] == "edit" %>
    <%= f.button " Edit Picture", id:"submitButton"  %>
    <% else %>
    <%= f.button " Post Picture", id:"submitButton"  %>
    <% end %>
  </div>
  <% end %>

<% end %>
<input type="hidden" name="parseForm">

app/views/pictures/show.html.erb
<div id="thePicture">
</div>