config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :pictures, only: [:create, :edit, :update, :destroy]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show] do
    resources :pictures, only: [:show]
  end
  resources :searches, only: [:index]

  root 'welcome#index'
  get '/users/:id/views', to: 'users#views', as: "views"
  post '/users/:id/association', to: 'users#association'
  get '/users/:id/follower_requests', to: 'users#follower_requests', as: "request"
  post '/searchPicture', to: 'searches#searchPicture'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Views</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>

  <body class="<%= controller_name %>_<%= action_name %>" >

    <% if user_signed_in? %>
      <input id="currentUserId" type="hidden" value="<%= current_user.id %>">

      <div class="navBar">
        <div class="column  1">
          <%= link_to image_tag("views-logo6.png", size:"100x45", class:"wiggle"), views_path(current_user) %>
        </div>

        <div class="column 2">
          <%= link_to image_tag("user-2-icon.png", size:"40x40", class:"wiggle"), current_user%>
        </div>

        <div class="column 3">
          <%= form_tag searchPicture_path, :method => 'get', id:"searchForm"  do %>
          <div class="ui icon input">
            <%= text_field_tag :type, params[:type], placeholder:"search...", class:"theSearchInput" %>
            <i class="circular search link icon" id="searchInputIcon"></i>
          </div>
          <span class="drop custom-dropdown custom-dropdown--white custom-dropdown--small">
              <select class="custom-dropdown__select custom-dropdown__select--white">
                  <option>User</option>
                  <option>Location</option>
                  <option>Tag</option>
              </select>
          </span>
          <!-- <%= submit_tag "Search", id: "searchSubmit"%> -->
          <% end %>
        </div>

        <div class="column 4 notification">
          <%= link_to image_tag("users-4-icon.png", size: "50x45", class:"wiggle"), request_path%>
        </div>

        <div class="column 5">
          <%= link_to image_tag("exitDoor.png", size:"50x50", class:"wiggle"), destroy_user_session_path, method: :delete%>
        </div>
      </div>

    <% else %>
      <div class="login">
        <%= image_tag("views-logo3.png", size:"126x55", class:"wiggle")%>
      </div>
    <% end %>

    <div class="errors">
    </div>
    <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>


    <div class="loader">
      <img src="/assets/Loading.gif">
    </div>

    <div id="yield">
      <%= yield %>
    </div>

  </body>
</html>